In [156]:
import os
import pandas as pd
import numpy as np

path_to_data = "../../query-results/test Demo_b27e5a74-f7fe-466a-9afa-5f9d9dfaeeff.csv"
converterS = {col: lambda x: "" if x=="[]" else x.strip("[]").split(", ") for col in ['Author_authorId','Author_displayName','Author_lastKnownAffiliationId']}
queryResults = pd.read_csv(path_to_data,converters=converterS)
queryResults

,Author_authorId,Author_rank,Author_displayName,Author_lastKnownAffiliationId,Paper_bookTitle,ConferenceInstance_conferenceInstanceId,Paper_date,Paper_docType,Paper_doi,FieldOfStudy_fieldOfStudyId,...,Paper_originalTitle,Paper_citationCount,Paper_estimatedCitation,Paper_firstPage,Paper_paperId,Paper_lastPage,Paper_publisher,Paper_referenceCount,Paper_paperTitle,Paper_year
0,"[109906890, 343224479, 1843180838, 2143783256,...","[14724, 14547, 17746, 14272, 15497, 15066, 157...","[Kevin W. Boyack, Ismael Rafols, Kamau Bobb, K...","[192454743, 60053951, 1298353152, 165450437, 1...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,Approaches to understanding and measuring inte...,353,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011
1,"[98572569, 2973595835]","[13831, 15269]","[Lutz Bornmann, Richard Williams]","[149899117, 107639228]",NaN,[],Fri Jan 01 00:11:00 UTC 2016,Journal,10.1016/j.joi.2016.09.013,"[90842384, 124101348, 41008148, 2522767166]",...,Sampling issues in bibliometric analysis: Resp...,9,9,1253.0,2537761553,1257.0,Elsevier,9,sampling issues in bibliometric analysis respo...,2016
2,"[2891685335, 2904803584]","[19418, 18544]","[Ronda J. Zhang, Fred Y. Ye]","[881766915, 881766915]",NaN,[],Wed Jan 01 00:02:00 UTC 2020,Journal,10.1016/j.joi.2019.100987,"[124101348, 2781188995, 41008148, 31258907, 99...",...,Measuring similarity for clarifying layer diff...,0,0,100987.0,2995611129,NaN,Elsevier,40,measuring similarity for clarifying layer diff...,2020
3,"[66010103, 1226625586, 2026323400]","[16421, 17200, 13840]","[Elías Sanz-Casado, Carlos García-Zorita, Rona...","[50357001, 50357001, 149213910]",NaN,[],Tue Jan 01 00:04:00 UTC 2013,Journal,10.1016/j.joi.2012.11.012,"[124101348, 12747933, 41008148, 106159729, 638...",...,The h-bubble,22,22,294.0,2086202982,300.0,Elsevier,36,the h bubble,2013
4,"[2165709822, 2631263729, 2915856988]","[15150, 18605, 16835]","[Giovanni Abramo, Ca D'Angelo, Tindaro Cicero]","[197604219, 116067653]",NaN,[],Sun Jan 01 00:01:00 UTC 2012,Journal,10.1016/j.joi.2011.12.003,"[124101348, 2778805511, 41008148, 23123220]",...,A sensitivity analysis of researchers’ product...,1,1,192.0,2964054951,201.0,NaN,0,a sensitivity analysis of researchers producti...,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,"[2907553680, 2908092644, 2908406310, 2950366139]","[19637, 18508, 21027, 19053]","[Peixin Li, Jian Du, Qianying Guo, Xiaoli Tang]","[1302978242, 1302978242, 1302978242, 1302978242]",NaN,[],Tue Jan 01 00:02:00 UTC 2019,Journal,10.1016/j.joi.2018.12.004,"[56739046, 124101348, 41008148, 2777626755, 29...",...,Measuring the knowledge translation and conver...,1,1,132.0,2906913315,148.0,Elsevier,51,measuring the knowledge translation and conver...,2019
1001,"[2026323400, 2118788044, 2151491403, 2232681441]","[13840, 16330, 20888, 20149]","[Ronald Rousseau, Fred Y. Ye, Joan Q. Liu, Mon...","[149213910, 881766915, 76130692, 76130692]",NaN,[],Tue Jan 01 00:01:00 UTC 2013,Journal,10.1016/j.joi.2012.11.002,"[33923547, 105795698]",...,"Ratios of h-cores, h-tails and uncited sources...",5,5,190.0,2018399266,197.0,Elsevier,19,ratios of h cores h tails and uncited sources ...,2013
1002,"[79825362, 72915928]","[15388, 20222]","[Klaus Wohlrabe, Daniel Birkmaier]","[1340728805, 8204097]",NaN,[],Wed Jan 01 00:10:00 UTC 2014,Journal,10.1016/j.joi.2014.08.005,"[2778805511, 82581908, 41008148, 111964698, 14...",...,The Matthew effect in economics reconsidered,6,6,880.0,2136804657,889.0,Elsevier,10,the matthew effect in economics reconsidered,2014
1003,[2140778852],[14353],[Ludo Waltman],[121797337],NaN,[],Fri Jan 01 00:05:00 UTC 2016,Journal,10.1016/j.joi.2016.02.007,"[124101348, 2779980791, 41008148, 83867959, 25...",...,A review of the literature on citation impact ...,260,375,365.0,767067438,391.0,Elsevier,350,a review of the literature on citation impact ...,2016
1004,[2104502493],[15286],[Mahdi Jalili],[82951845],NaN,[],Sat Jan 01 00:07:00 UTC 2011,Journal,10.1016/j.joi.2011.03.002,"[97970142, 34947359, 124101348, 41008148, 2983...",...,Error and attack tolerance of small-worldness ...,16,16,422.0,2070212390,430.0,Elsevier,40,error and attack tolerance of small worldness ...,2011

In [157]:
#queryResults[queryResults['Author_lastKnownAffiliationId']]
queryResults["LastAffiliateCount"] = queryResults['Author_lastKnownAffiliationId'].apply(len)
queryResults["AuthorCount"] = queryResults['Author_authorId'].apply(len)
queryResults[queryResults['LastAffiliateCount']==0]
queryResults

,Author_authorId,Author_rank,Author_displayName,Author_lastKnownAffiliationId,Paper_bookTitle,ConferenceInstance_conferenceInstanceId,Paper_date,Paper_docType,Paper_doi,FieldOfStudy_fieldOfStudyId,...,Paper_estimatedCitation,Paper_firstPage,Paper_paperId,Paper_lastPage,Paper_publisher,Paper_referenceCount,Paper_paperTitle,Paper_year,LastAffiliateCount,AuthorCount
0,"[109906890, 343224479, 1843180838, 2143783256,...","[14724, 14547, 17746, 14272, 15497, 15066, 157...","[Kevin W. Boyack, Ismael Rafols, Kamau Bobb, K...","[192454743, 60053951, 1298353152, 165450437, 1...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
1,"[98572569, 2973595835]","[13831, 15269]","[Lutz Bornmann, Richard Williams]","[149899117, 107639228]",NaN,[],Fri Jan 01 00:11:00 UTC 2016,Journal,10.1016/j.joi.2016.09.013,"[90842384, 124101348, 41008148, 2522767166]",...,9,1253.0,2537761553,1257.0,Elsevier,9,sampling issues in bibliometric analysis respo...,2016,2,2
2,"[2891685335, 2904803584]","[19418, 18544]","[Ronda J. Zhang, Fred Y. Ye]","[881766915, 881766915]",NaN,[],Wed Jan 01 00:02:00 UTC 2020,Journal,10.1016/j.joi.2019.100987,"[124101348, 2781188995, 41008148, 31258907, 99...",...,0,100987.0,2995611129,NaN,Elsevier,40,measuring similarity for clarifying layer diff...,2020,2,2
3,"[66010103, 1226625586, 2026323400]","[16421, 17200, 13840]","[Elías Sanz-Casado, Carlos García-Zorita, Rona...","[50357001, 50357001, 149213910]",NaN,[],Tue Jan 01 00:04:00 UTC 2013,Journal,10.1016/j.joi.2012.11.012,"[124101348, 12747933, 41008148, 106159729, 638...",...,22,294.0,2086202982,300.0,Elsevier,36,the h bubble,2013,3,3
4,"[2165709822, 2631263729, 2915856988]","[15150, 18605, 16835]","[Giovanni Abramo, Ca D'Angelo, Tindaro Cicero]","[197604219, 116067653]",NaN,[],Sun Jan 01 00:01:00 UTC 2012,Journal,10.1016/j.joi.2011.12.003,"[124101348, 2778805511, 41008148, 23123220]",...,1,192.0,2964054951,201.0,NaN,0,a sensitivity analysis of researchers producti...,2012,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,"[2907553680, 2908092644, 2908406310, 2950366139]","[19637, 18508, 21027, 19053]","[Peixin Li, Jian Du, Qianying Guo, Xiaoli Tang]","[1302978242, 1302978242, 1302978242, 1302978242]",NaN,[],Tue Jan 01 00:02:00 UTC 2019,Journal,10.1016/j.joi.2018.12.004,"[56739046, 124101348, 41008148, 2777626755, 29...",...,1,132.0,2906913315,148.0,Elsevier,51,measuring the knowledge translation and conver...,2019,4,4
1001,"[2026323400, 2118788044, 2151491403, 2232681441]","[13840, 16330, 20888, 20149]","[Ronald Rousseau, Fred Y. Ye, Joan Q. Liu, Mon...","[149213910, 881766915, 76130692, 76130692]",NaN,[],Tue Jan 01 00:01:00 UTC 2013,Journal,10.1016/j.joi.2012.11.002,"[33923547, 105795698]",...,5,190.0,2018399266,197.0,Elsevier,19,ratios of h cores h tails and uncited sources ...,2013,4,4
1002,"[79825362, 72915928]","[15388, 20222]","[Klaus Wohlrabe, Daniel Birkmaier]","[1340728805, 8204097]",NaN,[],Wed Jan 01 00:10:00 UTC 2014,Journal,10.1016/j.joi.2014.08.005,"[2778805511, 82581908, 41008148, 111964698, 14...",...,6,880.0,2136804657,889.0,Elsevier,10,the matthew effect in economics reconsidered,2014,2,2
1003,[2140778852],[14353],[Ludo Waltman],[121797337],NaN,[],Fri Jan 01 00:05:00 UTC 2016,Journal,10.1016/j.joi.2016.02.007,"[124101348, 2779980791, 41008148, 83867959, 25...",...,375,365.0,767067438,391.0,Elsevier,350,a review of the literature on citation impact ...,2016,1,1
1004,[2104502493],[15286],[Mahdi Jalili],[82951845],NaN,[],Sat Jan 01 00:07:00 UTC 2011,Journal,10.1016/j.joi.2011.03.002,"[97970142, 34947359, 124101348, 41008148, 2983...",...,16,422.0,2070212390,430.0,Elsevier,40,error and attack tolerance of small worldness ...,2011,1,1

In [158]:
queryResults2 = queryResults.loc[queryResults["LastAffiliateCount"]==queryResults["AuthorCount"],:].copy()
queryResults2

,Author_authorId,Author_rank,Author_displayName,Author_lastKnownAffiliationId,Paper_bookTitle,ConferenceInstance_conferenceInstanceId,Paper_date,Paper_docType,Paper_doi,FieldOfStudy_fieldOfStudyId,...,Paper_estimatedCitation,Paper_firstPage,Paper_paperId,Paper_lastPage,Paper_publisher,Paper_referenceCount,Paper_paperTitle,Paper_year,LastAffiliateCount,AuthorCount
0,"[109906890, 343224479, 1843180838, 2143783256,...","[14724, 14547, 17746, 14272, 15497, 15066, 157...","[Kevin W. Boyack, Ismael Rafols, Kamau Bobb, K...","[192454743, 60053951, 1298353152, 165450437, 1...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
1,"[98572569, 2973595835]","[13831, 15269]","[Lutz Bornmann, Richard Williams]","[149899117, 107639228]",NaN,[],Fri Jan 01 00:11:00 UTC 2016,Journal,10.1016/j.joi.2016.09.013,"[90842384, 124101348, 41008148, 2522767166]",...,9,1253.0,2537761553,1257.0,Elsevier,9,sampling issues in bibliometric analysis respo...,2016,2,2
2,"[2891685335, 2904803584]","[19418, 18544]","[Ronda J. Zhang, Fred Y. Ye]","[881766915, 881766915]",NaN,[],Wed Jan 01 00:02:00 UTC 2020,Journal,10.1016/j.joi.2019.100987,"[124101348, 2781188995, 41008148, 31258907, 99...",...,0,100987.0,2995611129,NaN,Elsevier,40,measuring similarity for clarifying layer diff...,2020,2,2
3,"[66010103, 1226625586, 2026323400]","[16421, 17200, 13840]","[Elías Sanz-Casado, Carlos García-Zorita, Rona...","[50357001, 50357001, 149213910]",NaN,[],Tue Jan 01 00:04:00 UTC 2013,Journal,10.1016/j.joi.2012.11.012,"[124101348, 12747933, 41008148, 106159729, 638...",...,22,294.0,2086202982,300.0,Elsevier,36,the h bubble,2013,3,3
5,"[2098541416, 2619865948]","[14704, 16515]","[Diana Hicks, Jian Wang]","[130701444, 99464096]",NaN,[],Thu Jan 01 00:01:00 UTC 2015,Journal,10.1016/j.joi.2014.12.006,"[56739046, 2992487645, 41008148, 57035238, 299...",...,15,197.0,2063580116,207.0,Elsevier,84,scientific teams self assembly fluidness and i...,2015,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,"[2907553680, 2908092644, 2908406310, 2950366139]","[19637, 18508, 21027, 19053]","[Peixin Li, Jian Du, Qianying Guo, Xiaoli Tang]","[1302978242, 1302978242, 1302978242, 1302978242]",NaN,[],Tue Jan 01 00:02:00 UTC 2019,Journal,10.1016/j.joi.2018.12.004,"[56739046, 124101348, 41008148, 2777626755, 29...",...,1,132.0,2906913315,148.0,Elsevier,51,measuring the knowledge translation and conver...,2019,4,4
1001,"[2026323400, 2118788044, 2151491403, 2232681441]","[13840, 16330, 20888, 20149]","[Ronald Rousseau, Fred Y. Ye, Joan Q. Liu, Mon...","[149213910, 881766915, 76130692, 76130692]",NaN,[],Tue Jan 01 00:01:00 UTC 2013,Journal,10.1016/j.joi.2012.11.002,"[33923547, 105795698]",...,5,190.0,2018399266,197.0,Elsevier,19,ratios of h cores h tails and uncited sources ...,2013,4,4
1002,"[79825362, 72915928]","[15388, 20222]","[Klaus Wohlrabe, Daniel Birkmaier]","[1340728805, 8204097]",NaN,[],Wed Jan 01 00:10:00 UTC 2014,Journal,10.1016/j.joi.2014.08.005,"[2778805511, 82581908, 41008148, 111964698, 14...",...,6,880.0,2136804657,889.0,Elsevier,10,the matthew effect in economics reconsidered,2014,2,2
1003,[2140778852],[14353],[Ludo Waltman],[121797337],NaN,[],Fri Jan 01 00:05:00 UTC 2016,Journal,10.1016/j.joi.2016.02.007,"[124101348, 2779980791, 41008148, 83867959, 25...",...,375,365.0,767067438,391.0,Elsevier,350,a review of the literature on citation impact ...,2016,1,1
1004,[2104502493],[15286],[Mahdi Jalili],[82951845],NaN,[],Sat Jan 01 00:07:00 UTC 2011,Journal,10.1016/j.joi.2011.03.002,"[97970142, 34947359, 124101348, 41008148, 2983...",...,16,422.0,2070212390,430.0,Elsevier,40,error and attack tolerance of small worldness ...,2011,1,1

In [170]:
Author_lastKnownAffiliationId = queryResults2.explode('Author_lastKnownAffiliationId')[['Author_lastKnownAffiliationId']]
Author_displayName = queryResults2.explode('Author_displayName')[['Author_displayName']]
PApairs = queryResults2.drop(['Author_lastKnownAffiliationId','Author_displayName'], axis = 1).explode('Author_authorId')
PApairs2 = pd.concat([Author_displayName,Author_lastKnownAffiliationId,PApairs], axis=1)
PApairs2

,Author_displayName,Author_lastKnownAffiliationId,Author_authorId,Author_rank,Paper_bookTitle,ConferenceInstance_conferenceInstanceId,Paper_date,Paper_docType,Paper_doi,FieldOfStudy_fieldOfStudyId,...,Paper_estimatedCitation,Paper_firstPage,Paper_paperId,Paper_lastPage,Paper_publisher,Paper_referenceCount,Paper_paperTitle,Paper_year,LastAffiliateCount,AuthorCount
0,Kevin W. Boyack,192454743,109906890,"[14724, 14547, 17746, 14272, 15497, 15066, 157...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
0,Ismael Rafols,60053951,343224479,"[14724, 14547, 17746, 14272, 15497, 15066, 157...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
0,Kamau Bobb,1298353152,1843180838,"[14724, 14547, 17746, 14272, 15497, 15066, 157...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
0,Katy Börner,165450437,2143783256,"[14724, 14547, 17746, 14272, 15497, 15066, 157...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
0,Joann Keyton,137902535,2147142969,"[14724, 14547, 17746, 14272, 15497, 15066, 157...",NaN,[],Sat Jan 01 00:01:00 UTC 2011,Journal,10.1016/j.joi.2010.06.004,"[124101348, 123757187, 41008148, 158251709, 63...",...,530,14.0,2163354434,26.0,Elsevier,50,approaches to understanding and measuring inte...,2011,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,Mona S. Wang,76130692,2232681441,"[13840, 16330, 20888, 20149]",NaN,[],Tue Jan 01 00:01:00 UTC 2013,Journal,10.1016/j.joi.2012.11.002,"[33923547, 105795698]",...,5,190.0,2018399266,197.0,Elsevier,19,ratios of h cores h tails and uncited sources ...,2013,4,4
1002,Klaus Wohlrabe,1340728805,79825362,"[15388, 20222]",NaN,[],Wed Jan 01 00:10:00 UTC 2014,Journal,10.1016/j.joi.2014.08.005,"[2778805511, 82581908, 41008148, 111964698, 14...",...,6,880.0,2136804657,889.0,Elsevier,10,the matthew effect in economics reconsidered,2014,2,2
1002,Daniel Birkmaier,8204097,72915928,"[15388, 20222]",NaN,[],Wed Jan 01 00:10:00 UTC 2014,Journal,10.1016/j.joi.2014.08.005,"[2778805511, 82581908, 41008148, 111964698, 14...",...,6,880.0,2136804657,889.0,Elsevier,10,the matthew effect in economics reconsidered,2014,2,2
1003,Ludo Waltman,121797337,2140778852,[14353],NaN,[],Fri Jan 01 00:05:00 UTC 2016,Journal,10.1016/j.joi.2016.02.007,"[124101348, 2779980791, 41008148, 83867959, 25...",...,375,365.0,767067438,391.0,Elsevier,350,a review of the literature on citation impact ...,2016,1,1
1004,Mahdi Jalili,82951845,2104502493,[15286],NaN,[],Sat Jan 01 00:07:00 UTC 2011,Journal,10.1016/j.joi.2011.03.002,"[97970142, 34947359, 124101348, 41008148, 2983...",...,16,422.0,2070212390,430.0,Elsevier,40,error and attack tolerance of small worldness ...,2011,1,1

In [171]:
PApairs3 = PApairs2[["Author_displayName","Author_lastKnownAffiliationId","Author_authorId","Paper_doi","Paper_originalTitle","Paper_paperId","Paper_year"]]
PApairs3.columns = ['author_name','last_known_affiliation_id','author_id','doi','original_title','paper_id','year']
PApairs3

,author_name,last_known_affiliation_id,author_id,doi,original_title,paper_id,year
0,Kevin W. Boyack,192454743,109906890,10.1016/j.joi.2010.06.004,Approaches to understanding and measuring inte...,2163354434,2011
0,Ismael Rafols,60053951,343224479,10.1016/j.joi.2010.06.004,Approaches to understanding and measuring inte...,2163354434,2011
0,Kamau Bobb,1298353152,1843180838,10.1016/j.joi.2010.06.004,Approaches to understanding and measuring inte...,2163354434,2011
0,Katy Börner,165450437,2143783256,10.1016/j.joi.2010.06.004,Approaches to understanding and measuring inte...,2163354434,2011
0,Joann Keyton,137902535,2147142969,10.1016/j.joi.2010.06.004,Approaches to understanding and measuring inte...,2163354434,2011
...,...,...,...,...,...,...,...
1001,Mona S. Wang,76130692,2232681441,10.1016/j.joi.2012.11.002,"Ratios of h-cores, h-tails and uncited sources...",2018399266,2013
1002,Klaus Wohlrabe,1340728805,79825362,10.1016/j.joi.2014.08.005,The Matthew effect in economics reconsidered,2136804657,2014
1002,Daniel Birkmaier,8204097,72915928,10.1016/j.joi.2014.08.005,The Matthew effect in economics reconsidered,2136804657,2014
1003,Ludo Waltman,121797337,2140778852,10.1016/j.joi.2016.02.007,A review of the literature on citation impact ...,767067438,2016
1004,Mahdi Jalili,82951845,2104502493,10.1016/j.joi.2011.03.002,Error and attack tolerance of small-worldness ...,2070212390,2011

In [172]:
PApairs3.to_csv('testInput.csv')